export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    'APP_NAME': 'EatLikePro',
    'THE_APP': 'The App',
    'CONTUCT_US': 'Contact us',
    'LOGIN_SIGNUP': 'Sign in',
    'JOIN_US': 'Add your place',
    'SUBMIT_AND_GET': 'Join us and get more customers',
    'LEARN_MORE': 'Learn more',
    'LOGIN': 'Login',
    'USERNAME': 'Username',
    'EMAIL': 'Email',
    'EMAIL_REQUIRED': 'Email required',
    'PASSWORD': 'Password',
    'PASSWORD_REQUIRED': 'Password required',
    'PASSWORD_MATCH_REQUIRED': 'Password match required',
    'REGISTER': 'Registration',
    'FIRST_NAME': 'First name',
    'FIRSTNAME_REQUIRED': 'First name required',
    'LAST_NAME': 'Last name',
    'REGISTERED_ON': 'Registered on',
    'ACCOUNT_TYPE': 'Account type',
    'LASTNAME_REQUIRED': 'Last name required',
    'CANCEL': 'Cancel',
    'REPEAT': 'repeat',
    'ADMIN': 'Admin',
    'HOME': 'Home',
    'CONTACT_US_QUICK_MSG': 'Leave your email and we will get back to you as soon as possible.',
    'GET_IN_TOUCH': 'Get in touch',
    'THANK_YOU_FOR_REGISTERING': 'Thank you for registering!',
    'ADD_NEW_PLACE': 'Add new place',
    'TO_YOUR_ACC': 'to your account',
    'TO_GET_STARTED': 'to get started',
    'FIND_PLACE': 'Search your place or point it on the map',
    'SELECTED_PLACE': 'Your selected place',
    'NAME': 'Name',
    'ADRESS': 'Adress',
    'PHONE': 'Phone',
    'WEBSITE': 'Website',
    'STEP_2': 'Step 2',
    'PAYMENT_OPTIONS': 'Payment options',
    'WORKING_HOURS': 'Working hours',
    'BACK': 'Back',
    'SAVE': 'Save',
    'STEP_3': 'Step 3',
    'BREAK': 'Break',
    'MONDAY': 'Monday',
    'TUESDAY': 'Tuesday',
    'WEDNESDAY': 'Wednesday',
    'THURSDAY': 'Thursday',
    'FRIDAY': 'Friday',
    'SATURDAY': 'Saturday',
    'SUNDAY': 'Sunday',
    'DISHES': 'Dishes',
    'SELECT_CURRENCY': 'Choose currency',
    'SELECT_DISHES': 'Select dishes',
    'SIZE': 'Size',
    'AVAILABILITY': 'Availability',
    'DESCRIPTION': 'Description',
    'PRICE': 'Price',
    'SUBMIT_PLACE': 'Submit Place',
    'DELIVERY_AVAILABLE': 'Delivery Available',
    'TAKEAWAY_AVAILABLE': 'Take Away Available',
    'PLACE_ADDED': 'Thank you, your place has been added!',
    'EDIT': 'Edit',
    'ABOUT_APP': 'About App',
    'FOR_USERS': 'For Application Users',
    'FOR_PLACES': 'For Places',
    'SEND_US_MESSAGE': 'Send us a message',
    'FULL_NAME': 'Full Name',
    'YOUR_MESSAGE': 'Your Message',
    'SEND_MESSAGE': 'Send Message',
    'DASHBOARD': 'Dashboard',
    'MY_PLACES': 'My Places',
    'PLACE': 'Place',
    'SELECT_COUNTRY_SITY_PLACE': 'Select country, city and place name',
    'OR_POINT_IT_ON_THE_MAP': 'Or point your place on the map',
    'SEND_PASSWORD_RESET': 'Send password-reset email',
    'MY_ACCOUNT': 'My Account',
    'USERS_REGISTERED': 'Users Registered',
    'PLACES_REGISTERED': 'Places Registered',
    'TOTAL_MEALS': 'Meals in total',
    'ADD_MEALS_FROM_ALL': 'Add Meals from all available',
    'OLD_PASSWORD_REQUIRED': 'Old Password required',
    'CHANGE_PASS': 'Change password',
    'OLD_PASSWORD': 'Old password',
    'LOGIN_OR_REGISTER': 'Place sign in or register before adding new place',
    'REGISTERED_WITH': 'Rgistered with',
    'OPENED': 'Opened',
    'OPENING_HOURS': 'Opening hours',
    'BREAK_HOURS': 'Break hours'
};
