export const LANG_ES_NAME = 'de';

export const LANG_ES_TRANS = {
    'APP_NAME': 'EatLikePro',
    'THE_APP': 'Application',
    'CONTUCT_US': 'Kontakt',
    'LOGIN_SIGNUP': 'Anmelden',
    'JOIN_US': 'Füge deinen Platz hinzu',
    'SUBMIT_AND_GET': 'Senden Sie Ihren Restaurant und erhalten Sie mehr Kunden',
    'LEARN_MORE': 'Mehr lernen',
    'LOGIN': 'Einloggen',
    'USERNAME': 'Benutzername',
    'EMAIL': 'Email',
    'EMAIL_REQUIRED': 'Email erforderlich',
    'PASSWORD': 'Kennwort',
    'PASSWORD_REQUIRED': 'Kennwort erforderlich',
    'PASSWORD_MATCH_REQUIRED': 'Passwörter übereinstimmen',
    'REGISTER': 'Anmeldung',
    'FIRST_NAME': 'Vorname',
    'FIRSTNAME_REQUIRED': 'Vorname erforderlich',
    'REGISTERED_ON': 'Mitglied seit',
    'ACCOUNT_TYPE': 'Konto Typ',
    'LAST_NAME': 'NachName',
    'LASTNAME_REQUIRED': 'NachName erforderlich',
    'CANCEL': 'stornieren',
    'REPEAT': 'wiederholen',
    'ADMIN': 'Admin',
    'HOME': 'Home',
    'CONTACT_US_QUICK_MSG': 'Hinterlassen Sie Ihre E-Mail und wir melden uns umgehend bei Ihnen.',
    'GET_IN_TOUCH': 'Kontaktiere uns',
    'THANK_YOU_FOR_REGISTERING': 'Danke für die Registrierung!',
    'ADD_NEW_PLACE': 'Neue Lokal hinzufügen',
    'TO_YOUR_ACC': 'zu deinem Account',
    'TO_GET_STARTED': 'um zu anfängen',
    'FIND_PLACE': 'Suchen Sie Ihren Platz oder zeigen Sie ihn auf der Karte',
    'SELECTED_PLACE': 'Ihr ausgewählter Ort',
    'NAME': 'Name',
    'ADRESS': 'Adresse',
    'PHONE': 'Telefon',
    'WEBSITE': 'Webseite',
    'STEP_2': 'Schritt 2',
    'PAYMENT_OPTIONS': 'Zahlungsmöglichkeiten',
    'WORKING_HOURS': 'Arbeitszeit',
    'BACK': 'Zurück',
    'SAVE': 'Speichern',
    'STEP_3': 'Schritt 3',
    'BREAK': 'Pause',
    'MONDAY': 'Montag',
    'TUESDAY': 'Dienstag',
    'WEDNESDAY': 'Mittwoch',
    'THURSDAY': 'Donnerstag',
    'FRIDAY': 'Freitag',
    'SATURDAY': 'Samstag',
    'SUNDAY': 'Sonntag',
    'DISHES': 'Gerichte',
    'SELECT_CURRENCY': 'Währung wählen',
    'SELECT_MEALS': 'Geschirr Wählen',
    'SIZE': 'Grösse',
    'AVAILABILITY': 'Verfügbarkeit',
    'DESCRIPTION': 'Beschreibung',
    'PRICE': 'Preis',
    'SUBMIT_PLACE': 'Ort eintragen',
    'DELIVERY_AVAILABLE': 'Lieferung Verfügbar',
    'TAKEAWAY_AVAILABLE': 'Mitnehmen Verfügbar',
    'PLACE_ADDED': 'Vielen Dank, Ihr Ort hinzugefügtt',
    'EDIT': 'Bearbeiten',
    'ABOUT_APP': 'Über App',
    'FOR_USERS': 'Für Application Benutzer',
    'FOR_PLACES': 'Für Orte',
    'SEND_US_MESSAGE': 'Schick uns eine Nachricht',
    'FULL_NAME': 'Vollständiger Name',
    'YOUR_MESSAGE': 'Ihre Nachricht',
    'SEND_MESSAGE': 'Nachricht Senden',
    'DASHBOARD': 'Dashboard',
    'MY_PLACES': 'Meine Orte',
    'PLACE': 'Ort',
    'SELECT_COUNTRY_SITY_PLACE': 'Wählen Sie Land und Ort',
    'OR_POINT_IT_ON_THE_MAP': 'Oder zeigen Sie Ihren Platz auf der Karte',
    'SEND_PASSWORD_RESET': 'E-Mail zum Zurücksetzen des Passworts senden',
    'MY_ACCOUNT': 'Mein Konto',
    'USERS_REGISTERED': 'Registriert Benutzer',
    'PLACES_REGISTERED': 'Registriert Orte',
    'TOTAL_MEALS': 'Mahlzeiten in Gesamt',
    'ADD_MEALS_FROM_ALL': 'Mahlzeiten von alle verfügbare hinzufügen',
    'OLD_PASSWORD_REQUIRED': 'Altes Passwort erforderlich',
    'CHANGE_PASS': 'Passwort ändern',
    'OLD_PASSWORD': 'Altes Passwort',
    'LOGIN_OR_REGISTER': 'Bitte vor dem Sie ein neues Ort hinzufügen loggen Sie sich ein oder registrieren Sie sich ',
    'REGISTERED_WITH': 'Registriert mit',
    'OPENED': 'geöffnet',
    'OPENING_HOURS': 'Öffnungszeiten',
    'BREAK_HOURS': 'Pausezeiten'
};
