export const LANG_ES_NAME = 'de';

export const LANG_ES_TRANS = {
    'APP_NAME': 'EatLikePro',
    'THE_APP': 'Application',
    'CONTUCT_US': 'Kontakt',
    'LOGIN_SIGNUP': 'Einloggen / Anmelden',
    'JOIN_US': 'Schließ dich uns an',
    'SUBMIT_AND_GET': 'Senden Sie Ihren Restaurant und erhalten Sie mehr Kunden',
    'LEARN_MORE': 'Mehr lernen',
    'LOGIN': 'Einloggen',
    'USERNAME': 'Benutzername',
    'EMAIL': 'Email',
    'EMAIL_REQUIRED': 'Email erforderlich',
    'PASSWORD': 'Kennwort',
    'PASSWORD_REQUIRED': 'Kennwort erforderlich',
    'PASSWORD_MATCH_REQUIRED': 'Passwörter übereinstimmen',
    'REGISTER': 'Anmeldung',
    'FIRST_NAME': 'Vorname',
    'FIRSTNAME_REQUIRED': 'Vorname erforderlich',
    'LAST_NAME': 'NachName',
    'LASTNAME_REQUIRED': 'NachName erforderlich',
    'CANCEL': 'stornieren',
    'REPEAT': 'wiederholen',
    'ADMIN': 'Admin',
    'HOME': 'Home',
    'CONTACT_US_QUICK_MSG': 'Hinterlassen Sie Ihre E-Mail und wir melden uns umgehend bei Ihnen.',
    'GET_IN_TOUCH': 'Kontaktiere uns',
    'THANK_YOU_FOR_REGISTERING': 'Danke für die Registrierung!'
};
