export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    'APP_NAME': 'EatLikePro',
    'THE_APP': 'The App',
    'CONTUCT_US': 'Contact us',
    'LOGIN_SIGNUP': 'Login / Sign up',
    'JOIN_US': 'Join us',
    'SUBMIT_AND_GET': 'Join us and get more customers',
    'LEARN_MORE': 'Learn more',
    'LOGIN': 'Login',
    'USERNAME': 'Username',
    'EMAIL': 'Email',
    'EMAIL_REQUIRED': 'Email required',
    'PASSWORD': 'Password',
    'PASSWORD_REQUIRED': 'Password required',
    'PASSWORD_MATCH_REQUIRED': 'Password match required',
    'REGISTER': 'Registration',
    'FIRST_NAME': 'First name',
    'FIRSTNAME_REQUIRED': 'First name required',
    'LAST_NAME': 'Last name',
    'LASTNAME_REQUIRED': 'Last name required',
    'CANCEL': 'Cancel',
    'REPEAT': 'repeat',
    'ADMIN': 'Admin',
    'HOME': 'Home',
    'CONTACT_US_QUICK_MSG': 'Leave your email and we will get back to you as soon as possible.',
    'GET_IN_TOUCH': 'Get in touch',
    'THANK_YOU_FOR_REGISTERING': 'Thank you for registering!',
    'ADD_NEW_PLACE': 'Add new place',
    'TO_YOUR_ACC': 'to your account',
    'TO_GET_STARTED': 'to get started',
    'FIND_PLACE': 'Search your place or point it on the map',
    'SELECTED_PLACE': 'Your selected place',
    'NAME': 'Name',
    'ADRESS': 'Adress',
    'PHONE': 'Phone',
    'WEBSITE': 'Website',
    'STEP_2': 'Step 2',
    'PAYMENT_OPTIONS': 'Payment options',
    'WORKING_HOURS': 'Working hours'
    'BACK': 'Back',
    'STEP_3': 'Step 3'
    'BREAK': 'Break',
    'MONDAY': 'Monday',
    'TUESDAY': 'Tuesday',
    'WEDNESDAY': 'Wednesday',
    'THURSDAY': 'Thursday',
    'FRIDAY': 'Friday',
    'SATURDAY': 'Saturday',
    'SUNDAY': 'Sunday'

};
